In [26]:
from tabulate import tabulate
from fractions import Fraction

def print_df(df):
    print(tabulate(df, headers = 'keys', tablefmt = 'psql'))

The fraction of 0.25 is 1/4

#### Extracting, Merging and Saving

In [21]:
import pandas as pd
from tabulate import tabulate

excel_file = pd.ExcelFile('Field Selection\\MoraE21 DB.xlsx')
fields_df = pd.read_excel(excel_file, 'MoraE21 All')
results_df = pd.read_excel(excel_file, '1stSem')

grp = fields_df.groupby(['Field'])

#Mean vaules of SGPA for fields
mean_df = grp.mean('SGPA').sort_values('SGPA' , ascending = False)
#print('\n','Mean vaules of SGPA for fields: ')

#First and Last people's SGPA of a paticular filed
first = pd.Series(name = 'first')
last = pd.Series(name = 'last')
for name,group in grp:
    first[name] = group['SGPA'].max()
    last[name] = group['SGPA'].min()

mean_df['First'] = first
mean_df['Last'] = last

print_df(mean_df)

cols = list(results_df.columns)
results_df = results_df.drop(columns = cols[-4:])

results_df = results_df.drop(columns = ['Name'])
merged_df = fields_df.merge(results_df, on = 'ID')

#Formatting Columns
cols = list(merged_df.columns)
merged_df = merged_df[cols[:5] + [cols[-1]] + cols[7:14] + cols[5:7]]
cols = list(merged_df.columns)
cols[4] = 'SGPA'
cols[-3] = 'Exact SGPA'
merged_df.columns = cols

merged_df.to_csv('Field Selection\\Final_results.csv', index = False)
print('Saved as CSV')

merged_df

mech_df = merged_df[merged_df["Field"] == 'ME'][["ID","Name","UOM Mail"]]
mech_df

+-----------+---------+---------+--------+
| Field     |    SGPA |   First |   Last |
|-----------+---------+---------+--------|
| BM        | 3.86467 |    4    |   3.69 |
| EN        | 3.84869 |    4    |   3.72 |
| CS        | 3.69729 |    4    |   3.06 |
| EE        | 3.46    |    3.75 |   2.96 |
| ME        | 3.28919 |    4    |   2.56 |
| CH        | 3.06    |    3.79 |   2.46 |
| MT        | 2.83341 |    3.81 |   1.99 |
| CE        | 2.39744 |    3.74 |   0    |
| Not Found | 0       |    0    |   0    |
+-----------+---------+---------+--------+
Saved as CSV

C:\Users\nuwan\AppData\Local\Temp\ipykernel_46436\566894840.py:15: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  first = pd.Series(name = 'first')
C:\Users\nuwan\AppData\Local\Temp\ipykernel_46436\566894840.py:16: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  last = pd.Series(name = 'last')
C:\Users\nuwan\AppData\Local\Temp\ipykernel_46436\566894840.py:17: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for name,group in grp:

          ID                       Name                      UOM Mail
4    210006L            ABEYRATHNA S.V.        abeyrathnasv.21@uom.lk
5    210007P         ABEYRATNE U.D.M.P.       abeyratneudmp.21@uom.lk
7    210009A    ABEYSINGHE A.M.K.K.S.B.    abeysingheamkksb.21@uom.lk
11   210013F            ABEYSINGHE M.P.        abeysinghemp.21@uom.lk
19   210021D        ADIKARAM W.K.D.N.E.       adikaramwkdne.21@uom.lk
..       ...                        ...                           ...
693  210692H           WEERASINGHE P.M.       weerasinghepm.21@uom.lk
720  210719B          WIJESEKARA P.N.B.       wijesekarapnb.21@uom.lk
724  210723G      WIJESURIYA M.W.A.D.I.     wijesuriyamwadi.21@uom.lk
730  210729F  WIMALARATHNA H.D.A.G.A.S.  wimalarathnahdagas.21@uom.lk
741  210740F               YUWARAJAN S.          yuwarajans.21@uom.lk

[99 rows x 3 columns]

#### Analysis

In [22]:
import pandas as pd

df = pd.read_csv('Field Selection\\Final_results.csv')
df = df.sort_values('Exact SGPA', ascending = False)

cols = list(df.columns)

new_df = df[['ID','Name','Sex','Field', 'SGPA']]
grp = new_df.groupby(['Field'])

#Males and Females
for name,group in grp:
    grp2 = group.groupby('Sex')
    if name != 'ME': continue
    for name2, group2 in grp2:
        if name2 == 'M': continue
        print(name,':')
        group2 = group2.sort_values('SGPA', ascending = False)
        group2 = group2.reset_index(drop = True)
        print(group2.shape[0])
        print(name2, print_df(group2))
        print_df(group2.describe())

ME :
14
+----+---------+-----------------------+-------+---------+--------+
|    | ID      | Name                  | Sex   | Field   |   SGPA |
|----+---------+-----------------------+-------+---------+--------|
|  0 | 210719B | WIJESEKARA P.N.B.     | F     | ME      |   4    |
|  1 | 210059B | BANDARA D.M.K.N.S.    | F     | ME      |   3.68 |
|  2 | 210654U | THUMARA LDK           | F     | ME      |   3.68 |
|  3 | 210656D | THUSHKARANEY S.       | F     | ME      |   3.64 |
|  4 | 210376T | MANISHI PRABASHA P.A. | F     | ME      |   3.43 |
|  5 | 210546P | RUBASINGHE L.K.       | F     | ME      |   3.29 |
|  6 | 210375N | MANDIS P.L.P.M.       | F     | ME      |   3.24 |
|  7 | 210428G | NIMESHA D.K.A.        | F     | ME      |   3.21 |
|  8 | 210126E | DILRINI W.G.          | F     | ME      |   3.19 |
|  9 | 210481K | PIYUMIKA G.D.S.T.     | F     | ME      |   3.13 |
| 10 | 210443X | PABODHA H.G.K.        | F     | ME      |   3.11 |
| 11 | 210270M | KALYANAPRIYA U.L.     | F     | ME      |   3.1  |
| 12 | 210461B | PERERA K.M.M.         | F     | ME      |   3.09 |
| 13 | 210244M | JAYARATHNE M.H.D.A.   | F     | ME      |   3.02 |
+----+---------+-----------------------+-------+---------+--------+
F None
+-------+-----------+
|       |      SGPA |
|-------+-----------|
| count | 14        |
| mean  |  3.34357  |
| std   |  0.295625 |
| min   |  3.02     |
| 25%   |  3.115    |
| 50%   |  3.225    |
| 75%   |  3.5875   |
| max   |  4        |
+-------+-----------+

C:\Users\nuwan\AppData\Local\Temp\ipykernel_46436\1024810782.py:12: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for name,group in grp:

In [38]:
import pandas as pd

df = pd.read_csv('Field Selection\\Final_results.csv')

result = df.pivot_table(index='Field', columns='Sex', aggfunc='size', fill_value=0)
result = pd.DataFrame(result.to_records())
result.rename(columns={'F': 'Female Count', 'M': 'Male Count'}, inplace=True)
result['No of Males per Female'] = result['Male Count'] / result['Female Count']

result = result.sort_values('No of Males per Female', ascending = False)
print_df(result)

+----+-----------+----------------+--------------+--------------------------+
|    | Field     |   Female Count |   Male Count |   No of Males per Female |
|----+-----------+----------------+--------------+--------------------------|
|  5 | EN        |             13 |           86 |                  6.61538 |
|  6 | ME        |             14 |           85 |                  6.07143 |
|  3 | CS        |             35 |          164 |                  4.68571 |
|  4 | EE        |             18 |           71 |                  3.94444 |
|  2 | CH        |             17 |           61 |                  3.58824 |
|  1 | CE        |             32 |           89 |                  2.78125 |
|  0 | BM        |              4 |           11 |                  2.75    |
|  7 | MT        |             14 |           30 |                  2.14286 |
|  8 | Not Found |              1 |            1 |                  1       |
+----+-----------+----------------+--------------+--------------------------+

In [41]:
import pandas as pd

df = pd.read_csv('Field Selection\\Final_results.csv')
cols = list(df.columns)
result = df[df.duplicated(subset=cols[6:12], keep=False)].sort_values(by=cols[6:12])
result = result.reset_index(drop = True, inplace = True)
result
df

,ID,Name,Sex,Field,SGPA,RANK,CSE,Math,EE,Fluid,Material,Mech,Exact SGPA,UOM Mail,Personal Email
0,210001R,AATHIF M.N.M.,M,CS,3.87,75,A-,A-,A,A+,A+,A,3.871429,aathifmnm.21@uom.lk,mohamedaathif100001@gmail.com
1,210003B,ABEWICKREMA A.S.J.,M,EN,3.79,125,A,A-,B,A,A+,A+,3.792857,abewickremaasj.21@uom.lk,sasindu.jananga@gmail.com
2,210004E,ABEYGUNAWARDANE R.A.S.,M,CS,3.61,278,A,B+,B,A,A,B+,3.607143,abeygunawardaneras.21@uom.lk,raminduanjana22171@gmail.com
3,210005H,ABEYRATHNA S.M.S.M.B.,M,EN,3.94,49,A-,A,A+,A+,A+,A,3.935714,abeyrathnasmsmb.21@uom.lk,sahanminidu2001@gmail.com
4,210006L,ABEYRATHNA S.V.,M,ME,3.37,429,A,C,B+,A,A,B+,3.371429,abeyrathnasv.21@uom.lk,saniruvinoshanofficial@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
741,210740F,YUWARAJAN S.,M,ME,3.45,372,A-,B,B,A-,A-,A-,3.450000,yuwarajans.21@uom.lk,skyuwarajan27@gmail.com
742,210741J,DINAKSHI P.K.S.,F,CE,1.61,725,D,C+,C,I-we,C+,C,1.607143,dinakshipks.21@uom.lk,dinakshipks00@gmail.com
743,210742M,VIDANAPATHIRANA R.C.,M,CH,3.51,337,B-,B,A,A,A,A,3.507143,vidanapathiranarc.21@uom.lk,rcvreshanchathuranga@gmail.com
744,210743R,NISSANKA G.T.,M,CE,2.85,625,C,B-,B,B+,B+,B+,2.850000,nissankagt.21@uom.lk,thisarugallage@gmail.com
745,210744V,EDIRISINGHE C.N.,M,CE,1.55,726,C+,I-we,I-we,B-,B-,C,1.550000,edirisinghecn.21@uom.lk,chanuda22@gmail.com

In [17]:
me_df = df.loc[(df['Field'] == "ME") ]
med_df = me_df.sort_values('SGPA', ascending=False)
med_df.sort_values('SGPA', ascending=False)
med_df.reset_index(drop = True, inplace = True)
med_df

,ID,Name,Sex,Field,SGPA,RANK,CSE,Math,EE,Fluid,Material,Mech,Exact SGPA,UOM Mail,Personal Email
0,210719B,WIJESEKARA P.N.B.,F,ME,4.00,1,A,A,A,A+,A,A+,4.000000,wijesekarapnb.21@uom.lk,navodiwijesekara75@gmail.com
1,210655A,THUSHARAGAN R.,M,ME,4.00,1,A,A,A,A+,A,A,4.000000,thusharaganr.21@uom.lk,thusha022001@gmail.com
2,210534D,RATHNAPRIYA K.W.S.A.,M,ME,4.00,1,A,A,A,A+,A+,A+,4.000000,rathnapriyakwsa.21@uom.lk,sachinarathnapriya@gmail.com
3,210192B,GUNARATNE K.A.A.N.,M,ME,3.94,49,A,A-,A+,A,A,A+,3.935714,gunaratnekaan.21@uom.lk,nimdulakaan@gmail.com
4,210664B,UMAKANTHAN K.,M,ME,3.81,113,A,B+,A+,A-,A,A,3.807143,umakanthank.21@uom.lk,umakanthan021@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,210348K,MADHUSANKHA G.D.,M,ME,3.04,577,C+,C+,A-,A-,A-,B+,3.042857,madhusankhagd.21@uom.lk,madhusankhams@gmail.com
95,210539X,RATHNAYAKE R.M.K.C.,M,ME,3.03,583,C+,B-,A-,B-,B+,A,3.028571,rathnayakermkc.21@uom.lk,kavishkachamodrathnayake@gmail.com
96,210244M,JAYARATHNE M.H.D.A.,F,ME,3.02,586,B+,B,B,B,B,B-,3.021429,jayarathnemhda.21@uom.lk,dulmijayarathne.dj@gmail.com
97,210145K,DISSANAYAKE D.M.N.M.B.,M,ME,3.01,589,B+,C+,C,A-,A,B,3.014286,dissanayakedmnmb.21@uom.lk,naveendissanayake7@gmail.com
98,210278U,KARUNATHILAKA M.P.R.S.,M,ME,2.56,677,B,C,B,A-,A-,Not Found,2.557143,karunathilakamprs.21@uom.lk,renukashehank17@gmail.com

In [47]:
import tabula

file_loc = r"D:\University of Moratuwa\Semester 2\MT 1814 Engineering Materials\Practical Groups ME (S2 In21) - 1.pdf"
dlist = tabula.read_pdf(file_loc, pages='all')

ndf = dlist[0]
cols = list(ndf.columns)
ndf.drop(cols[:3], axis=1)

lis = []
for row in ndf.itertuples():
    if(row[0] > 13): break
    print(row[4],"-",row[5])
    lis.append(row[4])
    
print(lis)

Got stderr: May 19, 2023 10:07:12 PM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFO: Your current java version is: 1.8.0_111
May 19, 2023 10:07:12 PM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFO: To get higher rendering speed on old java 1.8 or 9 versions,
May 19, 2023 10:07:12 PM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFO:   update to the latest 1.8 or 9 version (>= 1.8.0_191 or >= 9.0.4),
May 19, 2023 10:07:12 PM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFO:   or
May 19, 2023 10:07:12 PM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFO:   use the option -Dsun.java2d.cmm=sun.java2d.cmm.kcms.KcmsServiceProvider
May 19, 2023 10:07:12 PM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFO:   or call System.setProperty("sun.java2d.cmm", "sun.java2d.cmm.kcms.KcmsServiceProvider")

210312V - KUMARA U.G.N.
210317P - KUMARASINGHE K.A.T.K.
210320T - KUMARASINGHE M.H.A.D.N.
210323F - KUMBALATHARA K.A.A.K.
210327V - LAHIRU N.P.G.S.
210348K - MADHUSANKHA G.D.
210356H - MAHENDRA K.G.K.
210375N - MANDIS P.L.P.M.
210376T - MANISHI PRABASHA P.A.
210377X - MANUKULASOORIYA C.A.
210395B - MUNASINGHE B.S.S.M.
210674F - VISHWANATH B.A.M.P.
210684K - WEERAKOON W.M.D.C.
210691E - WEERASINGHE N.A.C.
['210312V', '210317P', '210320T', '210323F', '210327V', '210348K', '210356H', '210375N', '210376T', '210377X', '210395B', '210674F', '210684K', '210691E']

In [54]:
is_in_df = df["ID"].isin(lis)
new_df = df[is_in_df]
print_df(new_df)

â•­â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚     â”‚ ID      â”‚ Name                    â”‚ Sex   â”‚ Field   â”‚   SGPA â”‚   RANK â”‚ CSE   â”‚ Math   â”‚ EE   â”‚ Fluid   â”‚ Material   â”‚ Mech   â”‚   Exact SGPA â”‚ UOM Mail                    â”‚ Personal Email                  â”‚
â”œâ”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 310 â”‚ 210312V â”‚ KUMARA U.G.N.           â”‚ M     â”‚ ME      â”‚   3.09 â”‚    559 â”‚ A-    â”‚ B-     â”‚ C+   â”‚ A-      â”‚ A-         â”‚ C+     â”‚      3.08571 â”‚ kumaraugn.21@uom.lk         â”‚ nuwanthakumara999@gmail.com     â”‚
â”‚ 315 â”‚ 210317P â”‚ KUMARASINGHE K.A.T.K.   â”‚ M     â”‚ ME      â”‚   3.22 â”‚    503 â”‚ B-    â”‚ B      â”‚ B    â”‚ B       â”‚ A          â”‚ A      â”‚      3.22143 â”‚ kumarasinghekatk.21@uom.lk  â”‚ thinethkesara2002@gmail.com     â”‚
â”‚ 318 â”‚ 210320T â”‚ KUMARASINGHE M.H.A.D.N. â”‚ M     â”‚ ME      â”‚   3.16 â”‚    533 â”‚ B+    â”‚ C+     â”‚ A-   â”‚ B+      â”‚ B          â”‚ A-     â”‚      3.15714 â”‚ kumarasinghemhadn.21@uom.lk â”‚ dilshan99nayanajith@gmail.com   â”‚
â”‚ 321 â”‚ 210323F â”‚ KUMBALATHARA K.A.A.K.   â”‚ M     â”‚ ME      â”‚   3.23 â”‚    500 â”‚ B+    â”‚ B-     â”‚ B    â”‚ B+      â”‚ A          â”‚ B+     â”‚      3.22857 â”‚ kumbalatharakaak.21@uom.lk  â”‚ akashkithsara9999@gmail.com     â”‚
â”‚ 325 â”‚ 210327V â”‚ LAHIRU N.P.G.S.         â”‚ M     â”‚ ME      â”‚   3.33 â”‚    449 â”‚ B     â”‚ B      â”‚ B+   â”‚ A-      â”‚ B+         â”‚ A      â”‚      3.32857 â”‚ lahirunpgs.21@uom.lk        â”‚ sithijachess@gmail.com          â”‚
â”‚ 346 â”‚ 210348K â”‚ MADHUSANKHA G.D.        â”‚ M     â”‚ ME      â”‚   3.04 â”‚    577 â”‚ C+    â”‚ C+     â”‚ A-   â”‚ A-      â”‚ A-         â”‚ B+     â”‚      3.04286 â”‚ madhusankhagd.21@uom.lk     â”‚ madhusankhams@gmail.com         â”‚
â”‚ 355 â”‚ 210356H â”‚ MAHENDRA K.G.K.         â”‚ M     â”‚ ME      â”‚   3.23 â”‚    500 â”‚ B-    â”‚ B+     â”‚ B+   â”‚ A       â”‚ B+         â”‚ B      â”‚      3.22857 â”‚ mahendrakgk.21@uom.lk       â”‚ krishanmahendra2001@hotmail.com â”‚
â”‚ 374 â”‚ 210375N â”‚ MANDIS P.L.P.M.         â”‚ F     â”‚ ME      â”‚   3.24 â”‚    495 â”‚ A-    â”‚ B-     â”‚ A-   â”‚ B-      â”‚ A          â”‚ B-     â”‚      3.24286 â”‚ mandisplpm.21@uom.lk        â”‚ maleeshapamudi103@gmail.com     â”‚
â”‚ 375 â”‚ 210376T â”‚ MANISHI PRABASHA P.A.   â”‚ F     â”‚ ME      â”‚   3.43 â”‚    390 â”‚ B+    â”‚ B-     â”‚ A    â”‚ A       â”‚ A+         â”‚ B      â”‚      3.42857 â”‚ manishiprabashapa.21@uom.lk â”‚ manishiprabasha@gmail.com       â”‚
â”‚ 376 â”‚ 210377X â”‚ MANUKULASOORIYA C.A.    â”‚ M     â”‚ ME      â”‚   3.21 â”‚    512 â”‚ B+    â”‚ B      â”‚ B+   â”‚ B       â”‚ A-         â”‚ B      â”‚      3.20714 â”‚ manukulasooriyaca.21@uom.lk â”‚ chamikaabhimana@gmail.com       â”‚
â”‚ 394 â”‚ 210395B â”‚ MUNASINGHE B.S.S.M.     â”‚ M     â”‚ ME      â”‚   3.18 â”‚    522 â”‚ B     â”‚ C+     â”‚ B+   â”‚ B+      â”‚ A          â”‚ A-     â”‚      3.17857 â”‚ munasinghebssm.21@uom.lk    â”‚ sachirapcc@gmail.com            â”‚
â”‚ 675 â”‚ 210674F â”‚ VISHWANATH B.A.M.P.     â”‚ M     â”‚ ME      â”‚   3.29 â”‚    469 â”‚ B     â”‚ C+     â”‚ A-   â”‚ A       â”‚ A-         â”‚ A-     â”‚      3.29286 â”‚ vishwanathbamp.21@uom.lk    â”‚ stylempv@gmail.com              â”‚
â”‚ 685 â”‚ 210684K â”‚ WEERAKOON W.M.D.C.      â”‚ M     â”‚ ME      â”‚   3.22 â”‚    503 â”‚ A-    â”‚ C      â”‚ B    â”‚ B+      â”‚ A-         â”‚ A      â”‚      3.22143 â”‚ weerakoonwmdc.21@uom.lk     â”‚ dhanu2000uni@gmail.com          â”‚
â”‚ 692 â”‚ 210691E â”‚ WEERASINGHE N.A.C.      â”‚ M     â”‚ CE      â”‚   3.24 â”‚    499 â”‚ B     â”‚ C+     â”‚ B-   â”‚ A       â”‚ A          â”‚ A      â”‚      3.23571 â”‚ weerasinghenac.21@uom.lk    â”‚ amilachathuranga2070@gmail.com  â”‚
â•°â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯